#!/usr/bin/env python

def getComment(targetNum=4,featureNum=10):
  comment="""
  CREATE TABLE data(
  ID   INTEGER PRIMARY KEY AUTOINCREMENT,
  TARGET1  REAL NOT NULL,
  TARGET2  REAL NOT NULL,
  TARGET3  REAL NOT NULL,
  TARGET4  REAL NOT NULL,
  FEATURE1 REAL,
  FEATURE2 REAL,
  FEATURE3 REAL,
  FEATURE4 REAL,
  FEATURE5 REAL,
  FEATURE6 REAL,
  FEATURE7 REAL,
  FEATURE8 REAL,
  FEATURE9 REAL,
  FEATURE10 REAL
  )
  """
  return comment

